package mainmodule.util;

import java.util.Date;

@SuppressWarnings("SpellCheckingInspection")
public class Constants {
    public static final int BACKGROUND_IMAGES_SPEED = 5;
    public static final int Max_Width = 1280;
    public static final int Max_Height = 720;
    public static final int ATTACK_RATE = 150;
    public static final int AVATAR_SPEED = 4;
    public static final int BOSSBIRD_SPEED = 5;
    public static final int BOSS_1_WIDTH = 651;
    public static final int BOSS_1_HEIGHT = 509;
    public static final int BOSS_2_WIDTH = 187;
    public static final int BOSS_2_HEIGHT = 224;
    public static final int EGG_BULLET_SPEED = 12;
    public static final int EGG_BULLET_WIDTH = 136;
    public static final int EGG_BULLET_DURATION = 3200;
    public static final int EGG_BULLET_HEIGHT = 109;
    public static final int EGG_BULLET_EXPLOSION_SIZE = 250;
    public static final int EGG_BULLET_EXPLOSION_TIME = 200;
    public static final int BOSS_BIRD1_HEALTH = 50;
    public static final int BOSS_BIRD2_HEALTH = 50;
    public static final int AVATAR_BULLET_HEIGHT = 15;
    public static final int AVATAR_BULLET_WIDTH = 72;
    public static final int AVATAR_BULLET_DURATION = 3200;
    public static final int AVATAR_BULLET_DISTANCE_FROM_CENTER = 70;
    public static final int AVATAR_BACK_DISTANCE_FROM_CENTER = 130;
    public static final int AVATAR_BULLET_EXPLOSION_SIZE = 100;
    public static final int AVATAR_BULLET_SPEED = 10;
    public static final int AVATAR_BOMB_SPEED = 10;
    public static final int AVATAR_BOMB_HEIGHT = 15;
    public static final int AVATAR_BULLET_EXPLOSION_TIME = 100;
    public static final int AVATAR_BOMB_WIDTH = 72;
    public static final int AVATAR_BOMB_EXPLOSION_SIZE = 100;
    public static final int AVATAR_MISSLE_WIDTH = 55;
    public static final int AVATAR_MISSLE_HEIGHT = 36;
    public static final int AVATAR_MISSLE_DURATION = 3200;
    public static final int AVATAR_MISSLE_EXPLOSION_TIME = 300;
    public static final int AVATAR_MISLLE_SPEED = 20;
    public static final int AVATAR_GET_BACK_AFTER_BOOM = 40;
    public static final int AVATAR_MISSLE_DAMAGE_RATIO = 50;
    public static final int AVATAR_MISSLE_EXPLOSION_SIZE = 100;
    public static final int AVATAR_MISSLE_SPEED = 10;
    public static final int AVATAR_NORMAL_STATE_DURATION = 1000;
    public static final int AVATAR_NORMAL_BOMBING_STATE_DURATION = 1000;
    public static final int AVATAR_BLINK_STATE_DURATION = 300;
    public static final int AVATAR_MISSLE_STATE_DURATION = 2000;
    public static final int AVATAR_MISSLE_STATE_ATTACK_RATE = 1000;

    public static final int AVATAR_HEALTH = 400;
    public static final int BULLET_DURATION = 3200;
    public static final int BOSS_BIRD_STATE_SHOOTING = 1500;
    public static final int BOSS_BIRD_BULLET_Y = 189;
    public static final int BOSS_BIRD_BULLET_DURATION = 3200;
    public static final int BOSS_BIRD_BULLET_X = -76;
    public static final int BOSS_BIRD_STATE_SHOOTING_BOUND = 2;
    public static final int BOSS_BIRD_STATE_FLYING = 1500;
    public static final int BOSS_BIRD_STATE_FLYING_BOUND = 2;
    public static final int BOSS_BIRD_STATE_HITTED = 1500;
    public static final int BOSS_BIRD_STATE_HITTED_CYCLE_COUNT = 1;
    public static final int BOSS_BIRD_STATE_HITTED_BOUND = 2;
    public static final int BOSS_BIRD_STATE_TURN_TO_LEFT = 1500;
    public static final int BOSS_BIRD_STATE_TURN_TO_LEFT_CYCLE_COUNT = 1;
    public static final int BOSS_BIRD_STATE_TURN_TO_RIGHT = 1500;
    public static final int BOSS_BIRD_STATE_TURN_TO_RIGHT_CYCLE_COUNT = 1;
    public static final int BOSS_BIRD_STATE_DEATH = 1500;
    public static final int BOSS_BIRD_STATE_DEATH_CYCLE_COUNT = 1;
    public static final int BOSS_BIRD_STATE_RIGHT = 1500;
    public static final int BOSS_BIRD_STATE_RIGHT_CYCLE_COUNT = 1;
    public static final int BOSS_BIRD_STATE_LEFT = 1500;
    public static final int BOSS_BIRD_STATE_LEFT_CYCLE_COUNT = 1;
    public static final int BOSS_MINI_BIRD_SPEED = 1;
    public static final int BOSS_BIRD_STATE_SHOOTING_LEFT = 1500;
    public static final int BOSS_BIRD_STATE_SHOOTING_TO_LEFT_CYCLE_COUNT = 1;
    public static final int BOSS_BIRD_STATE_SHOOTING_RIGHT = 1500;
    public static final int BOSS_BIRD_STATE_SHOOTING_TO_RIGHT_CYCLE_COUNT = 1;
    public static final int MINI_BOSS_BULLET_HEIGHT = 66;
    public static final int MINI_BOSS_BULLET_WIDTH = 150;
    public static final int MINI_BOSS_BULLET_X = -33;
    public static final int MINI_BOSS_BULLET_Y = 75;
    public static final int MINI_BOSS_BULLET_SPEED = 5;
    public static int MINI_BOSS_BULLET_DURATION  = 3200;
    public static final int MINI_BOSS_EXPLOSION_SIZE = 100;
    public static final int MINI_BOSS_EXPLOSION_TIME = 100;

    public static final int MINI_BOSS_EGG_MAX_DISTANCE = 500;
    public static final int MINI_BOSS_EGG_MIN_DISTANCE = 100;
    public static final int MINI_BOSS_EGG_EXPLOSION_SIZE = 300;
    public static final int MINI_BOSS_EGG_HEIGHT = 106;
    public static final int MINI_BOSS_EGG_WIDTH = 118;
    public static final int MINI_BOSS_EGG_SPEED = 10;
    public static final int MINI_BOSS_EGG_HEALTH = 30;
    public static final int MINI_BOSS_EGG_EXPLOSION_TIME = 500;
    public static final int MINI_BOSS_BIRD_HEALTH = 100;
    public static final int BOSS_BIRD3_WIDTH = 900;
    public static final int BOSS_BIRD3_HEIGHT = 355;
    public static final int BOSS_BIRD3_HEALTH = 50;
    public static final int BOSS_BIRD3_SPEDD = 3;
    public static final int BOSS_BIRD_DOCTOR_WIDTH = 131;
    public static final int BOSS_BIRD_DOCTOR_HEIGHT = 201;
    public static final int BED_BOSS_BULLET_SPEED = 4;
    public static final int BED_BOSS_BULLET_EXPLOSION_SIZE = 50;
    public static final int BED_BOSS_BULLET_EXPLOSION_TIME = 200;
    public static final int BED_BOSS_BULLET_DURATION = 3200;
    public static final int DOCTOR_BOSS_BIRD_LEFT_WIDTH = 10;
    public static final int DOCTOR_BOSS_BIRD_LEFT_HEIGHT = 160 - BOSS_BIRD_DOCTOR_HEIGHT;
    public static final int DOCTOR_BOSS_BIRD_RIGHT_WIDTH = 770;
    public static final int DOCTOR_BOSS_BIRD_RIGHT_HEIGHT = 160 - BOSS_BIRD_DOCTOR_HEIGHT;
    public static final int BED_BOSS_BIRD_BULLET1_HEIGHT = 92;
    public static final int BED_BOSS_BIRD_BULLET1_WIDTH = 70;
    public static final int BED_BOSS_BIRD_BULLET2_HEIGHT = 72;
    public static final int BED_BOSS_BIRD_BULLET2_WIDTH = 98;
    public static final int BED_BOSS_BIRD_BULLET_DURATION = 3200;
    public static final int BED_BOSS_BIRD_BULLET3_HEIGHT = 88;
    public static final int BED_BOSS_BIRD_BULLET3_WIDTH = 47;
    public static final int BED_BOSS_BIRD_BULLET4_HEIGHT = 90;
    public static final int BED_BOSS_BIRD_BULLET4_WIDTH = 82;
    public static final int BED_BOSS_BIRD_BULLET_X = 683;
    public static final int BED_BOSS_BIRD_BULLET_Y = 10;
    public static final int DOCTOR_BIRD_BULLET_X = 72;
    public static final int DOCTOR_BIRD_BULLET_Y = -23;
    public static final int DOCTOR_BIRD_BULLET_DURATION = 3200;
    public static final int BOSS_BIRD_POULTRY_WIDTH = 157;
    public static final int BOSS_BIRD_POULTRY_HEIGHT = 114;
    public static final int BOSS_BIRD_POULTRY_EXPLOSION_SIZE = 200;
    public static final int BOSS_BIRD_POULTRY_EXPLOSION_TIME = 300;
    public static final int BOSS_BIRD_POULTRY_PROBABILITY = 400;
    public static final int BOSS_BIRD_POULTRY_DISTANCE = 140;
    public static int BOSS_BIRD_POULTRY_DURATION = 8200;
    public static final int BOSS_BIRD_POULTRY_X = Constants.Max_Width;
    public static final int BOSS_BIRDS_HEALTH = Constants.BOSS_BIRD2_HEALTH + Constants.BOSS_BIRD3_HEALTH + Constants.BOSS_BIRD1_HEALTH;
    public static final double FAR_FROM_OWNER_Y = 50;
    public static final int X_DISTANCE_1 = 70;
    public static final int Y_DISTANCE_1 = 150;
    public static final int X_DISTANCE_2 =  10;
    public static final int Y_DISTANCE_2 = 10;
    public static final int X_DISTANCE_3 = 5;
    public static final int Y_DISTANCE_3 = 20;
    public static final int X_DISTANCE_D = 10;
    public static final int Y_DISTANCE_D = 10;

    public static Long getCurrentTime() {
        return new Date().getTime();
    }

}
